### ISSUE TITLE
TODO: decide on project for non-HPP people

### ISSUE THREAD

**Issue by LukeRoantree4815162342** [LukeRoantree4815162342/QUB_DW_HighPerformancePython#1]
# Ideas So Far:

>Have them recreate the download -> install dependencies -> start Jupyter program

> Weather Forecaster CLI (using darksky.net API)

> File organiser/modifier CLI 

> Reddit/Twitter bot

**Comment by cduffy55** [comment]
I made a Tic-tac-toe app, see latest commit
